name       : kjsembed
version    : 5.49.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/portingAids/kjsembed-5.49.0.tar.xz : 15403504c1140b35a43e26bddfc95ccdf95787a0236e6c7d2b0e3853dd94ad61
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
