name       : kjsembed
version    : 5.48.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/portingAids/kjsembed-5.48.0.tar.xz : 1d63f306b1f980e402df1bf3cda37087796f5614df9cd9e32d650eb1fa78e448
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
