name       : kjsembed
version    : 5.65.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/portingAids/kjsembed-5.65.0.tar.xz : e6d919e6c87f7a38df623a4f5061cafa50b61fe10f9d4769f61f116f4e920d21
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
