name       : kjsembed
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/portingAids/kjsembed-5.36.0.tar.xz : 49bf01a91f227d7daa1b41f1e792054a814de4f1783c4a44a316123fbb938580
license    : LGPL-2.1
component  : programming
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
