name       : kjsembed
version    : 5.72.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/portingAids/kjsembed-5.72.0.tar.xz : bcd256e5fa8e928b35beb3e89ea163f7ece599789641a2ae694f2753cbdeeacf
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
