name       : kjsembed
version    : 5.39.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.39/portingAids/kjsembed-5.39.0.tar.xz : ebcd97eaa6a5e36f6af7201e10f716aaab3a8cda984ce6b115a8274072f778c4
license    : LGPL-2.1
component  : programming
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
