name       : kjsembed
version    : 5.57.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/portingAids/kjsembed-5.57.0.tar.xz : 741aae8db274febe7e5d0d10dc99271efc590b2465d2c4d4e4a9162d2b36e3b4
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
