name       : kjsembed
version    : 5.45.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/portingAids/kjsembed-5.45.0.tar.xz : 2e2ee5189a239444b543d56b492d47c7e988b8610164ea19b9830d6e4b5e5496
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
