name       : kjsembed
version    : 5.87.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/portingAids/kjsembed-5.87.0.tar.xz : fb45291488b2701401d6af0bcd9c85664fcf3d21c7b83f28c4a26f34cf300b49
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
