name       : kjsembed
version    : 5.44.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/portingAids/kjsembed-5.44.0.tar.xz : f3be43e553ce3a944ffe67b3cab704335bad70880854c02eedd4bbd29dbde134
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
