name       : kjsembed
version    : 5.91.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/portingAids/kjsembed-5.91.0.tar.xz : c0d07cba5fc4173279335f8bf696eb6e013696a19eadd3851f4f428942399e88
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
