name       : kjsembed
version    : 5.51.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/portingAids/kjsembed-5.51.0.tar.xz : b44eb2fda23de3165415bfc2809467cb3713e1595c3583883ba67d28973c8056
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
