name       : kjsembed
version    : 5.50.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/portingAids/kjsembed-5.50.0.tar.xz : ead875ad54c63782a59ad01a18cd9c904e2c668862474ec1e39ab6083afa4cc5
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
