name       : kjsembed
version    : 5.83.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/portingAids/kjsembed-5.83.0.tar.xz : 3aaf4098636bb33142f8787d7f670e5f44a6e482e3916f022afafa771f8cac29
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
