name       : kjsembed
version    : 5.66.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/portingAids/kjsembed-5.66.0.tar.xz : 58fe647901b69167b7c66a284c3181c2eda9c3b751548eb43bfe0795d10eb0ce
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
