name       : kjsembed
version    : 5.85.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/portingAids/kjsembed-5.85.0.tar.xz : 413236f69e6c04fb3df05fb60847ee8fe51d8fd08d46abea79605e789ecb17c9
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
