name       : kjsembed
version    : 5.88.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/portingAids/kjsembed-5.88.0.tar.xz : 1700da37c2ef365aec02f6d4dee08173d0746ede911ca5a50b9f51960363af2e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
