name       : kjsembed
version    : 5.46.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/portingAids/kjsembed-5.46.0.tar.xz : 02b31a8f5754f6e96069a88c62af4dfc783865548f2d67474afa538c2288828e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
