name       : kjsembed
version    : 5.77.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/portingAids/kjsembed-5.77.0.tar.xz : fc7efebc3d7b40066e215ca61cc8e15e0d1e389706277c5f6b972b96020cf229
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
