name       : kjsembed
version    : 5.67.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/portingAids/kjsembed-5.67.0.tar.xz : 376bae467ed3129362d1a975a07d088f3d175a786330e789f81c79b2cd8a5603
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
