name       : kjsembed
version    : 5.96.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/portingAids/kjsembed-5.96.0.tar.xz : 000ee3f2965f8f783e0e54f526fc505686b45c833f53d73515fae1b0890510fd
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
