name       : kjsembed
version    : 5.81.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/portingAids/kjsembed-5.81.0.tar.xz : 090f2e3e25f35566a4afd6a9369a867124c22a590b02d53e9d0fb49a99fb6a7e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
