name       : kjsembed
version    : 5.107.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/portingAids/kjsembed-5.107.0.tar.xz : 726e499a415d9967096c81584478a1114128152ca7a062359e2a2ae0976f31ab
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
