name       : kjsembed
version    : 5.75.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/portingAids/kjsembed-5.75.0.tar.xz : 1127c6f558f9272881ec733a21caa0b93376d9a86ffd2a7558fc299fb3a7efe3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
