name       : kjsembed
version    : 5.41.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/portingAids/kjsembed-5.41.0.tar.xz : a71f358ff922d56b5fe7cbd19a0e9183106d1961883ca54f1db2e5d47281abef
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
