name       : kjsembed
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/portingAids/kjsembed-5.32.0.tar.xz : e447e847dd46af4016ec0f15c12a02d09252a2e844a3d6c596fbb5ba59251740
license    : LGPL-2.1
component  : programming
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
