name       : kjsembed
version    : 5.55.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/portingAids/kjsembed-5.55.0.tar.xz : 7470bfbd2842fdfadd26838ed424717b2d245ad5998272252212afe445000936
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
