name       : kjsembed
version    : 5.40.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/portingAids/kjsembed-5.40.0.tar.xz : 2dda7d9c5c19fa7450adf66ee8bd74365441d9e519ceca21a50557aa48218339
license    : LGPL-2.1
component  : programming
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
