name       : kjsembed
version    : 5.70.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/portingAids/kjsembed-5.70.0.tar.xz : f5c6352ec1791c0e8757631322cf07df4eb138449add7d79881076f89572e624
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
