name       : kjsembed
version    : 5.58.0
release    : 24
source     :
    - https://download.kde.org/stable/frameworks/5.58/portingAids/kjsembed-5.58.0.tar.xz : ffbcd9de767d62497db146acd7bcaeaa59b3f6b418616d4562d1a2269048131d
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
