name       : kjsembed
version    : 5.100.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/portingAids/kjsembed-5.100.0.tar.xz : a7864c09cc7407b045b829fc3ba4a084fea18d183c3a867795c864d326734cf0
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
