name       : kjsembed
version    : 5.71.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/portingAids/kjsembed-5.71.0.tar.xz : 9352a31b5f735d71d6db4b09825ca01adb337e37f2b0cfce48c679e932238486
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
