name       : kjsembed
version    : 5.62.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/portingAids/kjsembed-5.62.0.tar.xz : 3763c5f67fa92803b5003a41c5b696524be3d0528018a3d5643abc25b161c23b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
