name       : kjsembed
version    : 5.92.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/portingAids/kjsembed-5.92.0.tar.xz : d7c26538a0b7ac804565840d61df2681ea4b729abb6ecfbfcae3c20536ca6035
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
