name       : kjsembed
version    : 5.99.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/portingAids/kjsembed-5.99.0.tar.xz : fc89d03bf59732f9436ae88dd20505a49d58a7c7bd46858263cb0462d2262070
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
