name       : kjsembed
version    : 5.79.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/portingAids/kjsembed-5.79.0.tar.xz : fe1694f5ae939f049ba2585112218d1dcbafede6974f486b51619d1a6bc172a2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
