name       : kjsembed
version    : 5.101.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/portingAids/kjsembed-5.101.0.tar.xz : 0520a3f31b1a8c946d8cf51725745be44fad92e0f909b335d75d330875308c01
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
