name       : kjsembed
version    : 5.43.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/portingAids/kjsembed-5.43.0.tar.xz : 1e9a97c03007e20aaad631cf1cfcdc3d5950cab5dd9aa189b6fad03c21e70c86
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
