name       : kjsembed
version    : 5.82.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/portingAids/kjsembed-5.82.0.tar.xz : cdc4e725d6d584ce81661fce246dff4d0f7c8d2fa3fc24a499977a5795c9c10f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
