name       : kjsembed
version    : 5.47.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/portingAids/kjsembed-5.47.0.tar.xz : ad41e142662e619b2c61babeff12053b52cf8cd4e90789fb4707e2fbc7d89680
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
