name       : kjsembed
version    : 5.106.0
release    : 65
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/portingAids/kjsembed-5.106.0.tar.xz : 09846926fd1bea728febe61f6e7d2171a9a508f3038cc4265274b8f5386d153e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
