name       : kjsembed
version    : 5.63.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/portingAids/kjsembed-5.63.0.tar.xz : eb444305618f04c0e804ea661956e217f57549b71c6fae94f1222a1b36355903
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
