name       : kjsembed
version    : 5.64.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/portingAids/kjsembed-5.64.0.tar.xz : 939226116cb47fd66dc45a41baa3c0f45b7ab904ec7674088ced3df5c7bae62e
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
rundeps    :
    - devel :
        - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
