name       : kjsembed
version    : 5.105.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/portingAids/kjsembed-5.105.0.tar.xz : 8a8af23563345649c19adec044a86ee5f37d64c90444d51058cd1c271d1b23b5
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
