name       : kjsembed
version    : 5.109.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/portingAids/kjsembed-5.109.0.tar.xz : 39ad0b51b57adef1780b256f4d44078d50718eae60e40faf2fb7b6e52dc078dd
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
